### PR TITLE
Fix return error only

### PR DESCRIPTION
**Pull request by longquan0104**
Sorry I forget to add http.go when commit

### CODE REVIEW

**Comment by jbreeden-sfx** [comment]
FWIW: I tested the change to http.go on some of my queries and it looks mostly OK to me.

I'm loading a list of items, each with a child object that is federated (the first service resolves only the `id`, and another service returns the rest of the objects fields). Before this change, if any one federated child object failed on the remote service, I get all out failure and no data returned. After this change, I get a full list of data - albeit the failed item is missing the federated fields of the child - and one error explaining the one failed item.

One question though (and this may be a future enhancement): For the element that failed federation I still get the `id` field from the service that resolved the parent. That seems ok at first, but there are some field in the other service that are marked as required. Does it actually make sense to return the partial result with the `id` field in this case?

To make it more concrete, I basically have this schema in service 1:

```gql
type Query {
  getParents() [Parent]!
}

type Parent {
  id: ID!
  child: Child!
}

type Child implements Node {
  id: ID!
}
```

and this in service 2:

```gql
type Child implements Node {
  id: ID!
  name: String!
}
```

And now when I run this query:

```gql
{
  getParents {
    child {
      id
      name
    }
  }
}
```

I get `Child` objects with an `id` but no `name`, even though it's a required field.

This seems like it breaks the schema agreement to me. The service is now returning an object without some of the required fields. I think in those failure cases we may need to bubble up the null value to the parent, and so on, until we reach a nullable parent. That would keep to the GQL spec.

**Comment by AlecAivazis** [comment]
Hello again! No worries about forgetting a few places, it's a pretty small change so it's easy to take in a few at a time. Once the merge conflict is resolved, I'll merge it in.

Also to answer your question, you are absolutely right. This does violate the schema agreement. Would you please copy and paste what you just wrote into a new issue? If it's something you want to try to address, I can offer some guidance on how I would approach it. Otherwise, someone will get to it eventually

**Comment by jbreeden-sfx** [comment]
Sure thing! Created #100

I probably won't be able to address this right away. I'm about to start ramping up on a new project. But if I get a chance I'll ping you for guidance. Thanks!

**Comment by AlecAivazis** [comment]
@longquan0104 since rebasing on master, it seems that the only net change is a single new empty line. Can you confirm? If so, I'll go ahead and close this

**Comment by longquan0104** [comment]
Sorry that I edited wrong line. I just re-edit it

**Comment by AlecAivazis** [comment]
Ah there we go! Alright, looks good to me

**Pull request merged**
