### PR TITLE
Enable merging of unions in merger

### PR DESCRIPTION
**Pull request by edwinmo-splunk**
A union's possibleTypes includes all members of the union and not
itself.
See issue #74: https://github.com/nautilus/gateway/issues/74

### CODE REVIEW

**Comment by edwinmo-splunk** [comment]
@AlecAivazis please take a look whenever is convenient for you 😄

**Comment by edwinmo-splunk** [comment]
Huh, I don't see any failures. I think it might not like the fact that I forked the repo and the PR comes from it?

```
PASS
coverage: 90.5% of statements
ok  	github.com/nautilus/gateway	0.097s	coverage: 90.5% of statements
flag needs an argument: -repotoken
```

I'll create one in the main repo and see if that works.

**Comment by AlecAivazis** [comment]
Yea it looks like the issue happened when coverage was being reported. I’m not sure why that failed but I’ll take a look tonight

**Comment by AlecAivazis** [comment]
This looks good to me. I'm going to merge it since the tests are passing and it should go green when its merged.

Thanks again for the contribution!

**Pull request merged**
